@token = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Mzk1MzM5OTN9.b206eKxu6_aWCeJ2RIfD__BAo0nzPr1YQDidKzw72jw

### Users Index Action
GET http://localhost:3000/users

### Users Create Action
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "harrow",
  "email": "harrow@ninth.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions Create Action
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "harrow@ninth.com",
  "password": "password"
}

### Entries Index Action
GET http://localhost:3000/entries
Authorization: Bearer {{token}}

### Entries Create Action
POST http://localhost:3000/entries
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "user_id": 1,
  "title": "Saw Charon today",
  "notes": "Saw charon today, just like everyday. It was large and ugly as usual",
  "telescope_type": "N/A",
  "start_time": "12:00 AM",
  "end_time": "3:00 AM",
  "location": "Castle Drearburh",
  "declination": "21° 04′ 07″",
  "right_ascention": "15h 08m 13s",
  "magnification": "N/A",
  "seeing_conditions": "Poor",
  "filters": "None",
  "date": "12/02/21",
  "observed_bodies": [1,3]
}

###
GET http://localhost:3000/entries/1

###
DELETE http://localhost:3000/entries/9
###

get http://localhost:3000/home