### Users Index Action
GET http://localhost:3000/users

### Users Create Action
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "gideon",
  "email": "gideon@ninth.com",
  "password": "password"
}